import Head from "next/head"

export default function AccountSetting()
{
    return (
        <>
        <Head>
        <title>MVR-帳號頁面</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            Account
        </main>
        </>
    )
}