import Head from 'next/head'
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import Link from 'next/link';
import { useState } from 'react';
import { BiShow } from 'react-icons/bi'

function Password()
{
    const [passwordShown, setPasswordShown] = useState(false);

    const togglePassword = () => {
        setPasswordShown(!passwordShown);
    }
    return (
        <>
            <Form.Group className="mb-3" controlId="formBasicPassword">
                <div className='d-flex align-items-center mb-1'>
                    <Form.Label className='flex-grow-1'>密碼</Form.Label>
                    <Button variant="light" onClick={togglePassword}>
                        <BiShow/>
                    </Button>
                </div>
                <Form.Control required type={passwordShown ? "text" : "password"} name="password" placeholder="輸入密碼" />
            </Form.Group>
        </>
    )
}

function LoginForm()
{
    const handleLogin = (event: any) => {
        event.preventDefault();
        if (event.target.account.value == "tkuim@gmail.com" && event.target.password.value == "tkuim")
        {
            window.alert("登入成功!!");
            window.location.replace("/userPage/userSetting")
        } else {
            window.alert("登入失敗!!");
        }
    }
    return (
        <>
        <div className='d-flex justify-content-center mt-4'>
            <Form onSubmit={handleLogin} className='bg-white rounded w-25 p-3'>
                <h2 className='text-center mb-3'>使用者登入</h2>
                <Form.Group className="mb-3" controlId="formBasicEmail">
                    <Form.Label>帳號</Form.Label>
                    <Form.Control required type="email" name='account' placeholder="輸入帳號" />
                </Form.Group>
                <Password />
                <div className='d-flex justify-content-around gap-5'>
                    <Link href="/userPage/register" legacyBehavior passHref>
                        <Button variant="primary" className='w-50'>註冊帳號</Button>
                    </Link>
                    <Button variant="primary" type="submit" className='w-50'>登入</Button>
                </div>
            </Form>
        </div>
        </>
    )
}

export default function Login()
{
    return (
        <>
        <Head>
        <title>MVR-登入</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <LoginForm />
        </main>
        </>
    )
}