import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import { useState } from 'react';
import { BiShow } from 'react-icons/bi'
import Head from 'next/head';

function Password()
{
    const [passwordShown, setPasswordShown] = useState(false);

    const togglePassword = () => {
        setPasswordShown(!passwordShown);
    }
    return (
        <>
            <Form.Group className="mb-3" controlId="formBasicPassword">
                <div className='d-flex align-items-center mb-1'>
                    <Form.Label className='flex-grow-1'>密碼</Form.Label>
                    <Button variant="light" onClick={togglePassword}>
                        <BiShow />
                    </Button>
                </div>
                    <Form.Control required type={passwordShown ? "text" : "password"} placeholder="輸入密碼" />
            </Form.Group>
        </>
    )
}

export default function Register()
{
    return (
        <>
        <Head>
        <title>MVR-註冊帳號</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <div className='d-flex justify-content-center mt-4'>
                <Form className='bg-white rounded w-25 p-3'>
                    <h2 className='text-center mb-3'>註冊</h2>
                    <Form.Group className="mb-3" controlId="formBasicEmail">
                        <Form.Label>帳號</Form.Label>
                        <Form.Control required type="email" placeholder="輸入帳號" />
                    </Form.Group>
                    <Password />
                    <div className='d-flex justify-content-center'>
                        <Button variant="primary" type="submit" className='w-50'>註冊帳號</Button>
                    </div>
                </Form>
            </div>
        </main>
        </>
    )
}