import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import { useState } from 'react';
import { BiShow } from 'react-icons/bi'
import Head from 'next/head';

function Password()
{
    const [passwordShown, setPasswordShown] = useState(false);

    const togglePassword = () => {
        setPasswordShown(!passwordShown);
    }
    return (
        <>
            <Form.Group className="mb-3" controlId="formBasicPassword">
                    <Form.Label>密碼</Form.Label>
                    <Form.Control required type={passwordShown ? "text" : "password"} placeholder="輸入密碼" />
            </Form.Group>
            <Button variant="light" onClick={togglePassword}>
                <BiShow />
            </Button>
        </>
    )
}

export default function Register()
{
    return (
        <>
        <Head>
        <title>MVR-註冊帳號</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <h1 className='text-center m-5'>註冊畫面</h1>
            <div className='d-flex justify-content-center'>
                <Form>
                    <Form.Group className="mb-3" controlId="formBasicEmail">
                        <Form.Label>帳號</Form.Label>
                        <Form.Control required type="email" placeholder="輸入帳號" />
                    </Form.Group>
                    <Password />
                    <Button variant="primary" type="submit">註冊帳號</Button>
                </Form>
            </div>
        </main>
        </>
    )
}