import ListGroup from 'react-bootstrap/ListGroup';
import Head from "next/head"
import Link from 'next/link';

function Menu()
{
    return (
    <ListGroup className='gap-2 m-3 bg-white'>
        <Link href="accountSetting" legacyBehavior passHref>
            <ListGroup.Item action>更改帳號</ListGroup.Item>
        </Link>
        <Link href="passwordSetting" legacyBehavior passHref>
            <ListGroup.Item action>更改密碼</ListGroup.Item>
        </Link>
        <Link href="friendList" legacyBehavior passHref>
            <ListGroup.Item action>好友清單</ListGroup.Item>
        </Link>
    </ListGroup>
    )
}

export default function UserSetting()
{
    return (
        <>
        <Head>
        <title>MVR-使用者設定</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <Menu/>
        </main>
        </>
    )
}