import Head from 'next/head'
import Carousel  from 'react-bootstrap/Carousel'
import Image from 'next/legacy/image';

function PhotoCarousel()
{
  return (
    <div className='d-flex justify-content-center mt-4'>
      <Carousel className='w-75'>
        <Carousel.Item>
          <Image src="/photoCarousel/interface.png" alt="Login UI" width="1500" height="1000" className='w-100'/>
        </Carousel.Item>
        <Carousel.Item>
          <Image src="/photoCarousel/main_menu.PNG" alt="Main menu" width="1500" height="1000" className='w-100'/>
        </Carousel.Item>
        <Carousel.Item>
          <Image src="/photoCarousel/world.png" alt="Choose world" width="1500" height="1000" className='w-100'/>
        </Carousel.Item>
        <Carousel.Item>
          <Image src="/photoCarousel/event_world.png" alt="Choose world" width="1500" height="1000" className='w-100'/>
        </Carousel.Item>
        <Carousel.Item>
          <Image src="/photoCarousel/shop1.PNG" alt="Choose world" width="1500" height="1000" className='w-100'/>
        </Carousel.Item>
      </Carousel>
    </div>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>MVR-首頁</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <PhotoCarousel />
      </main>
    </>
  )
}
