import Head from 'next/head'
import Carousel  from 'react-bootstrap/Carousel'
import Image from 'next/legacy/image';

function PhotoCarousel()
{
  return (
    <div className='d-flex justify-content-center'>
    <Carousel className='w-75'>
      <Carousel.Item>
        <Image src="/photoCarousel/1.jpg" alt="Picture 1" width="1500" height="1000" className='w-100'/>
      </Carousel.Item>
      <Carousel.Item>
        <Image src="/photoCarousel/1.jpg" alt="Picture 1" width="1500" height="1000" className='w-100'/>
      </Carousel.Item>
      <Carousel.Item>
        <Image src="/photoCarousel/2.jpg" alt="Picture 2" width="1500" height="1000" className='w-100'/>
      </Carousel.Item>
      <Carousel.Item>
        <Image src="/photoCarousel/3.jpg" alt="Picture 3" width="1500" height="1000" className='w-100'/>
      </Carousel.Item>
      <Carousel.Item>
        <Image src="/photoCarousel/4.jpg" alt="Picture 4" width="1500" height="1000" className='w-100'/>
      </Carousel.Item>
    </Carousel>
    </div>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>MVR-首頁</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-center m-5'>首頁</h1>
        <PhotoCarousel />
      </main>
    </>
  )
}
