import Head from 'next/head'

export default function IntroduceTeam()
{
    return (
        <>
        <Head>
        <title>MVR-團隊成員</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <h1 className='text-center m-5'>介紹團隊成員</h1>
        </main>
        </>
    )
}