import Head from 'next/head'
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';

function LoginForm()
{
    return (
        <div className='d-flex justify-content-center'>
            <Form>
                <Form.Group className="mb-3" controlId="formBasicEmail">
                    <Form.Label>帳號</Form.Label>
                    <Form.Control type="email" placeholder="輸入帳號" />
                </Form.Group>
                <Form.Group className="mb-3" controlId="formBasicPassword">
                    <Form.Label>密碼</Form.Label>
                    <Form.Control type="password" placeholder="輸入密碼" />
                </Form.Group>
            <Button variant="primary" type="submit">
                登入
            </Button>
            </Form>
        </div>
    )
}

export default function Login()
{
    return (
        <>
        <Head>
        <title>MVR-登入</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <h1 className='text-center m-5'>登入畫面</h1>
            <LoginForm />
        </main>
        </>
    )
}